name: Generate Release version info

on:
  push:
    tags:
      - "v*.*.*"  # vYY.MM.Patch example v23.08.00 etc.

jobs:
  generate_config:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"

      - name: Create config for Linux
        run: |
          cd installer
          mkdir build && cd build
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/installer/src/requirements.txt
          python ${{ github.workspace }}/installer/src/generate_config.py -v ${{ github.ref_name }}

      - name: Release version_info.json      
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/build/*
            ${{ github.workspace }}/installer/tools/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

