name: Generate Release version info

on:
  push:
    tags:
      - "v*.*.*"  # vYY.MM.Patch example v23.08.00 etc.

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Sensing-Dev version info
        run: |
          mkdir build && cd build
          echo "{" > version_info.json
          echo "\"Sensing-Dev\" : \"${GITHUB_REF#refs/tags/}\"" >> version_info.json
          echo "}" >> version_info.json

      - name: Add component version info
        run: |
          python ${GITHUB_WORKSPACE}/installer/scripts/get_component_version.py ${GITHUB_WORKSPACE}/installer/config.yml ${GITHUB_WORKSPACE}/build/version_info.json

      - name: Upload version_info.json
        uses: actions/upload-artifact@v2
        with:
          name: version_info.json
          path: build/version_info.json

      - name: Release version_info.json      
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/version_info.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}