libraries:
  aravis:
    name: aravis
    pkg_sha: "ed580a77eed2c0999d74dd875dd704b4acd2d90c61f00252aacfd43a76f28cbf"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "83076e1ddda04d4b232303c91ac87f3478e52be2a83fd7776cb8cd04ff96507a"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31"

  ion_kit:
    name: ion-kit
    pkg_sha: "87e42eb84c36674151eca5741e5a455fd3b1141a4cc84927f4f26cb553aa341b"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.2.5"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "e3bde8fce1b293d2db25bbfb0244e7c3245e523b7d64bf78ef26b5585e585959"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.3.5"


