libraries:
  aravis:
    name: aravis
    pkg_sha: "8f4fff574eb0ec809882977d679baea101a7fb59b68411435b245ae3d7b6dc54"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "2b68d3d61da13aaf3af9897f2b205c2a93ebe3ff49dc757a95265bb656cd2d97"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31"

  pygobject:
    name: pygobject
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    git_repo: "https://gitlab.gnome.org/GNOME/pygobject.git"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    pkg_sha: "8a6d593eba5887e21b9e9c0256d789233ff5c26e7858c7916e163d0a5fdf3aec"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.0.0"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "bdcf560332bf90dc07ebd50d931f86003fc8cbd54336009e03828d8aa45f965d"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.2.8"


