libraries:
  aravis:
    name: aravis
    pkg_sha: "ed580a77eed2c0999d74dd875dd704b4acd2d90c61f00252aacfd43a76f28cbf"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "83076e1ddda04d4b232303c91ac87f3478e52be2a83fd7776cb8cd04ff96507a"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31"

  ion_kit:
    name: ion-kit
    pkg_sha: "d85c31b70e128b7f22143cb2a91234f5e12e040094b5f74be950bf6620becd55"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.2.3"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "579cddbe612ecc970a20c53e7ecfe7e8fa3ce19485b33d48b1bfcfc81aa1c604"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.3.3"


