libraries:
  aravis:
    name: aravis
    pkg_sha: "a215a9b5d5d86b5eac9b970f2a17fe4b0238f458a5730a33f9c513bb9cfbc39e"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "8a59d45af9682eab1ca90156e4aa131a4fd6d840d0096cb6b3704d81f538ec56"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31"

  ion_kit:
    name: ion-kit
    pkg_sha: "edb523794467cd737833032db3965a3960f2ca58f195635bb347683400152641"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.1.0"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "bdcf560332bf90dc07ebd50d931f86003fc8cbd54336009e03828d8aa45f965d"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.2.8"


