libraries:
  aravis:
    name: aravis
    pkg_sha: "7d540ed479514c74adeb2ccb8d0626bcf93077cdedb4f5f91640203054960fdc"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "ceb7685e8e9c46be7fc1791ce5be66513e2aa45eb2920164e1eb4c84dbe0eba7"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31"

  ion_kit:
    name: ion-kit
    pkg_sha: "75bf579f5465d67a4e21ffca2eaf0325216cc184c4b77d2f0b7f9cec139f9842"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v1.8.3"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "bdcf560332bf90dc07ebd50d931f86003fc8cbd54336009e03828d8aa45f965d"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.2.8"


