libraries:
  aravis:
    name: aravis
    pkg_sha: "502552906e5cb52396c5f2bcdb670e3eddedc90b079635db94bc2f8152ebfdbc"
    git_repo: "https://github.com/Sensing-Dev/aravis.git"
    version: "v0.8.31.post1"

  aravis_dep:
    name: aravis_dep
    pkg_sha: "1b7370acd4139a33f252abc109ee9a38083856848379a93e34118564e787d47f"
    git_repo: "" # use recipe here for appropriate version
    version: "v0.8.31.post1"

  ion_kit:
    name: ion-kit
    pkg_sha: "6714b46f4f9f6db0806e78e69e1fee6188e520a5dfca5b134d1e007ae410fa33"
    git_repo: "https://github.com/fixstars/ion-kit.git"
    version: "v3.2.6"

  opencv:
    name: opencv
    pkg_sha: "bff38466091c313dac21a0b73eea8278316a89c1d434c6f0b10697e087670168"
    git_repo: "https://github.com/opencv/opencv"
    version: "4.10.0"

  gendc_separator:
    name: gendc_separator
    pkg_sha: "e3bde8fce1b293d2db25bbfb0244e7c3245e523b7d64bf78ef26b5585e585959"
    git_repo: "https://github.com/Sensing-Dev/GenDC.git"
    version: "v0.3.5"


